## Projection of v2 in v1

In [24]:
import numpy as np

In [25]:
print("Hello world")

Hello world


In [26]:
v1=np.array([1,2,3])
v2=np.array([4,5,6])

In [27]:
ans=np.dot(v1,v2)

In [28]:
ans

32

In [29]:
mod=np.sqrt(np.dot(v1,v1))

In [30]:
ans=ans/(mod*v1)

In [31]:
ans

array([8.55235974, 4.27617987, 2.85078658])

## Linear Independence Of 3 vctors


In [42]:
vec=np.array([[1,2,3],[4,5,6],[7,8,9]])


In [48]:
vec

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
ans=np.linalg.matrix_rank(vec)

In [44]:
lol=len(vec)

In [45]:
lol

3

In [52]:
det=np.linalg.det(vec)

## Check orthogonality

In [59]:
q=np.array([[4,-2,7],[-11,3,9],[2,8,7]])

In [60]:
q_trans=q.T

In [65]:
res=np.dot(q,q.T)

In [69]:
flag=np.identity(len(q))

In [71]:
if(np.allclose(res,flag)):
    print("Orthogonal")
else:
    print("Bye")

Bye


## Solve the system of equn

In [72]:
v1=np.array([[3,1,7],[1,2,2],[9,3,4]])

In [73]:
values=np.array([9,8,11])

In [77]:
np.linalg.solve(v1,values)

array([-0.25882353,  3.18823529,  0.94117647])

## using user defined function

In [78]:
a=np.array([[2,4,2],[3,9,11],[8,16,8]])

In [91]:
def inverse(a):
    if(np.linalg.det(a) !=0):
        identity=np.identity(len(a))
        inverse_a=identity/a
        print(inverse_a)
    print("NOt possible as det is 0")

In [92]:
inverse(a)

NOt possible as det is 0


In [93]:
rank_of_a=np.linalg.matrix_rank(a)

In [94]:
rank_of_a

2

## Cosine angle

In [96]:
v1=np.array([1,2,3])

In [97]:
v2=np.array([4,5,6])

In [98]:
mod_v1=(np.dot(v1,v1))

In [99]:
mod_v2=np.dot(v2,v2)

In [104]:
mod=np.sqrt(mod_v1*mod_v2)

In [105]:
mod

32.83291031876401

In [106]:
cosine= np.dot(v1,v2)/mod

In [107]:
cosine

0.9746318461970762

## Cross product

In [113]:
def cross_product(v1,v2):
    sin=np.sqrt(1-cosine*cosine)
    ans=mod*sin
    print(ans)

In [114]:
cross_product(v1,v2)

7.348469228349542


## New Question